### ISSUE TITLE
Unsupported expression: x => x.CreateClient()     Extension methods (here: HttpClientFactoryExtensions.CreateClient) may not be used in setup / verification expressions.

### ISSUE THREAD

**Issue by TanvirArjel** [maxkagamine/Moq.Contrib.HttpClient#2]
The following code:

    Mock<HttpMessageHandler> handler = new Mock<HttpMessageHandler>(MockBehavior.Strict);
    IHttpClientFactory factory = handler.CreateClientFactory();

    // Named clients can be configured as well (overriding the default)
    Mock.Get(factory).Setup(x => x.CreateClient())
             .Returns(() =>
             {
                    HttpClient client = handler.CreateClient();
                    client.BaseAddress = new Uri("https://example.com");
                    return client;
             });

Throwing the following error:

>System.NotSupportedException : Unsupported expression: x => x.CreateClient()
    Extension methods (here: HttpClientFactoryExtensions.CreateClient) may not be used in setup / verification expressions.

Note: I am trying to mock following code:

     private readonly HttpClient _skrillHttpClient;
     public SkrillService(IHttpClientFactory httpClientFactory)
     {
         _skrillHttpClient = httpClientFactory.CreateClient();
        _skrillHttpClient.BaseAddress = new Uri("https://www.skrill.com");
     }

**Comment by maxkagamine** [comment]
Hi TanvirArjel,

In your Setup, you're missing the client name in the call to `x.CreateClient()`, so what you're getting is actually the extension method [`HttpClientFactoryExtensions.CreateClient()`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclientfactoryextensions.createclient?view=dotnet-plat-ext-3.1) rather than the [`CreateClient(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory.createclient) on `IHttpClientFactory`.

If you're using a named client for SkrillService, adding it to the Setup should solve the problem:

```
Mock.Get(factory).Setup(x => x.CreateClient("skrillClient"))
```

If not, you can just leave that whole `Mock.Get()` out; the factory returned from `CreateClientFactory()` has [a catch-all Setup](https://github.com/maxkagamine/Moq.Contrib.HttpClient/blob/7a65e2b02fc6e8b484a3b72364009b0069ec7933/src/Moq.Contrib.HttpClient/MockHttpMessageHandlerExtensions.cs#L42-L53) for the default client.

(Looks like you figured it out while I was typing this. I'll leave it here anyway in case anyone else has this problem.)

**Comment by TanvirArjel** [comment]
@maxkagamine, Yes! I have understood this after posting the issue and that's why I have closed this. By the way, thank you for your response.

**Comment by TanvirArjel** [comment]
@maxkagamine By the way, I am getting the following exception:

>Handler did not return a response message.

Here is my setup:

      private readonly Mock<IHttpClientFactory> _mockHttpClientFactory = new Mock<IHttpClientFactory>();

        private readonly Mock<HttpMessageHandler> _mockHander;
        private readonly HttpClient _httpClient;
        public SkrillServiceTests()
        {
            _mockHander = new Mock<HttpMessageHandler>(MockBehavior.Loose);
            _httpClient = _mockHander.CreateClient();
            _httpClient.BaseAddress = new Uri("https://www.skrill.com");
        }

       public async Task TestMethod()
       {
            // Mock the handler

            _mockHander.SetupRequestSequence("https://www.skrill.com/app/pay.pl")
                .ReturnsResponse(HttpStatusCode.OK, s => s.Content = new StringContent("<?xml version='1.0' encoding='UTF-8'?><response><sid>5e281d1376d92ba789ca7f0583e045d4</sid></response>"))
                .ReturnsResponse(HttpStatusCode.OK, s => s.Content = new StringContent("<?xml version='1.0' encoding='UTF-8'?><response><transaction><amount>1.20</amount><currency>EUR</currency><id>497029</id><status>2</status><status_msg>processed</status_msg></transaction></response>"));

            // setup the method call
            _mockHttpClientFactory.Setup(x => x.CreateClient(It.IsAny<string>()))
                                 .Returns(_httpClient);
       }

**Comment by maxkagamine** [comment]
The only things here that jump out to me are:

1. You can just do `.ReturnsResponse("<?xml ...")` (the `configure` action is really only there for setting headers, and it defaults to ok if you only give it a string)
2. If you use `CreateClientFactory` in your constructor instead and do `_mockHttpClientFactory.CreateClient()` when you construct the SkrillService, you won't need to set up the client in each test ("setup the method call")

Other than that, maybe check where you're making the request, to make sure the url is matching the setup? If you switch it to `MockBehavior.Strict`, the exception will tell you the url that was requested, like this:

```
    Moq.MockException : HttpMessageHandler.SendAsync(Method: GET, RequestUri: 'https://example.com/value2', Version: 2.0, Content: <null>, Headers:
    {
    }, System.Threading.CancellationToken) invocation failed with mock behavior Strict.
    All invocations on the mock must have a corresponding setup.
```

(I changed [this line](https://github.com/maxkagamine/Moq.Contrib.HttpClient/blob/master/test/Moq.Contrib.HttpClient.Test/SequenceExtensionsTests.cs#L51) to "value2" so it'd throw.)

**Comment by TanvirArjel** [comment]
>Other than that, maybe check where you're making the request, to make sure the url is matching the setup?

Are query strings also taken into account during URL matching?

**Comment by maxkagamine** [comment]
When specifying a url, no, it has to match exactly. There's an example of [matching with query params here](https://github.com/maxkagamine/Moq.Contrib.HttpClient/blob/7a65e2b02fc6e8b484a3b72364009b0069ec7933/test/Moq.Contrib.HttpClient.Test/RequestExtensionsTests.cs#L198-L230). This example uses Flurl (a url parser/builder) to either build the url with known params or to match against the params themselves.

In your case, assuming you don't know the query string ahead of time, you can use the request predicate as seen on line 215 there or [here in the readme](https://github.com/maxkagamine/Moq.Contrib.HttpClient/#matching-requests-by-headers-json-query-params-etc) and check RequestUrl (you can do this with or without Flurl).

**Comment by TanvirArjel** [comment]
@maxkagamine Here is the method I am trying to test:

       public async Task ExecutePayoutRequestAsync(long userId, long transactionId, decimal payoutAmount)
        {
            try
            {
                string merchantAccount = Configuration.GetValue<string>("Srkill:MerchantAccount");
                string merchantApiPassword = Configuration.GetValue<string>("Srkill:MerchantApiPassword");
                string userSkrillAccount = await _unitOfWork.Repository<UserPayoutAccount>()
                    .GetEntities(upc => upc.UserId == userId && upc.AccountTypeId == 2)
                    .Select(upc => upc.AccountNo).FirstOrDefaultAsync();

                string invoiceNumber = Guid.NewGuid().ToString();

                Dictionary<string, string> transferRequestQueryString = new Dictionary<string, string>
                {
                    ["action"] = "prepare",
                    ["email"] = merchantAccount,
                    ["password"] = merchantApiPassword,
                    ["amount"] = payoutAmount.ToString(CultureInfo.InvariantCulture),
                    ["currency"] = "USD",
                    ["bnf_email"] = userSkrillAccount,
                    ["subject"] = "Test balance payout.",
                    ["note"] = "Your Test balance payout is on your way.",
                    ["frn_trn_id"] = invoiceNumber,
                };

                string payoutJson = JsonConvert.SerializeObject(transferRequestQueryString);

                PayoutRequestAndResponse payoutRequestAndResponse = new PayoutRequestAndResponse()
                {
                    TransactionId = transactionId,
                    RequestSent = payoutJson
                };

                _unitOfWork.ResetContextState();
                _unitOfWork.Repository<PayoutRequestAndResponse>().InsertEntity(payoutRequestAndResponse);

                string transferRequestUri = QueryHelpers.AddQueryString("/app/pay.pl", transferRequestQueryString);
                HttpResponseMessage transferRequestResponse = await _skrillHttpClient.GetAsync(transferRequestUri);
                if (transferRequestResponse.IsSuccessStatusCode)
                {
                    string transferRequestResponseString = await transferRequestResponse.Content.ReadAsStringAsync();
                    if (transferRequestResponseString.Contains("sid", StringComparison.OrdinalIgnoreCase))
                    {
                        string sid = transferRequestResponseString.XmlDeserialize<string>("sid");
                        Dictionary<string, string> transferExecutionQueryString = new Dictionary<string, string>()
                        {
                            ["action"] = "transfer",
                            ["sid"] = sid
                        };

                        string transferExecutionUri = QueryHelpers.AddQueryString("/app/pay.pl", transferRequestQueryString);
                        HttpResponseMessage transferExectionResponse = await _skrillHttpClient.GetAsync(transferExecutionUri);
                        if (transferExectionResponse.IsSuccessStatusCode)
                        {
                            string transferExectionResponseString = await transferRequestResponse.Content.ReadAsStringAsync();
                            SkrillPayoutReponseDto skrillTransactionDetials = transferExectionResponseString.XmlDeserialize<SkrillPayoutReponseDto>("transaction");

                            string skrillResponseJson = JsonConvert.SerializeObject(skrillTransactionDetials);

                            payoutRequestAndResponse.ResponseReceived = skrillResponseJson;
                            payoutRequestAndResponse.IsSuccessful = true;

                            GlotsAlotTransaction transaction = await _unitOfWork.Repository<GlotsAlotTransaction>()
                                .GetEntities(tr => tr.TransactionId == transactionId).FirstOrDefaultAsync();
                            transaction.InvoiceNumber = invoiceNumber;
                            transaction.FundingReferenceId = skrillTransactionDetials.Id;
                            transaction.CompletedAtUtc = DateTime.UtcNow;

                            _unitOfWork.Repository<GlotsAlotTransaction>().UpdateEntity(transaction);

                            TransactionDetails transactionDetails = await _unitOfWork.Repository<TransactionDetails>()
                                .GetEntities(td => td.TransactionId == transactionId).FirstOrDefaultAsync();
                            transactionDetails.Status = TransactionStatus.Completed;
                            _unitOfWork.Repository<TransactionDetails>().UpdateEntity(transactionDetails);
                        }
                    }
                    else
                    {
                        string error = transferRequestResponseString.XmlDeserialize<string>("error_msg");
                        payoutRequestAndResponse.ResponseReceived = error;
                        payoutRequestAndResponse.IsSuccessful = false;
                    }
                }
                else
                {
                    string payoutResponse = await transferRequestResponse.Content.ReadAsStringAsync();
                    payoutRequestAndResponse.ResponseReceived = payoutResponse;
                    payoutRequestAndResponse.IsSuccessful = false;
                }

                await _unitOfWork.SaveChangesAsync();
            }
            catch (Exception exception)
            {
                var methodParams = new { UserId = userId, TransactionId = transactionId, PayoutAmount = payoutAmount };
                await _exceptionLogger.LogExceptionAsync(exception, methodParams);
                throw;
            }
        }

Note: Please only look at the HttpClient calls. Now please tell me what should be exact mocking.

I need to get response from the following two lines:
1. await _skrillHttpClient.GetAsync(transferRequestUri);
2. await _skrillHttpClient.GetAsync(transferExecutionUri);

**Comment by maxkagamine** [comment]
I see. I would suggest actually not using SetupRequestSequence, but rather explicitly mock the urls that you expect to be requested. That way your test will also verify that it's making the _correct_ requests (for example, with the right `bnf_email` the first time and the right `sid` the second time). Since the second request requires the `sid` from the first response, mocking it this way will still ensure the "transfer execution" happens after "transfer request".

In that case, using [Flurl](https://flurl.dev/docs/fluent-url/) may actually make this easier, and then you can do basically [the same thing I did here](https://github.com/maxkagamine/Moq.Contrib.HttpClient/blob/7a65e2b02fc6e8b484a3b72364009b0069ec7933/test/Moq.Contrib.HttpClient.Test/RequestExtensionsTests.cs#L198-L230). Something like this:

```csharp
// Using a request predicate to look for the right query params
handler.SetupRequest(HttpMethod.Get, r =>
{
    Url url = r.RequestUri;
    return url.Path == "https://www.skrill.com/app/pay.pl" &&
        url.QueryParams["action"].Equals("prepare") &&
        url.QueryParams["email"].Equals(merchantAccount) &&
        // whatever else is important
})
    .ReturnsResponse("your xml");

// Alternatively, building and matching the exact url with query string
var transferExecutionUrl = "https://www.skrill.com/app/pay.pl"
    .SetQueryParam("action", "transfer")
    .SetQueryParam("sid", sid);

handler.SetupRequest(HttpMethod.Get, transferExecutionUrl)
    .ReturnsResponse("your xml");
```

**Comment by TanvirArjel** [comment]
@maxkagamine Have query strings value to exactly matched? There is a GUID value in the query string that is being randomly generated on the method call.

**Comment by maxkagamine** [comment]
If you use the request predicate, you don't need to check every query param, just whichever you want to make sure are being passed correctly. You could ignore `frn_trn_id`, or just check that it's there (regardless of what it's set to), or even try parsing it as a guid if you want to make sure it's the right format.

The boolean you return will determine whether or not the requested url should pass and return that response; you can do whatever url checking you feel is necessary.

**Comment by TanvirArjel** [comment]
@maxkagamine Finally everything is working as expected. A huge huge thanks to you. Please stay safe and sound.

**Comment by maxkagamine** [comment]
Glad I could help!
