### ISSUE TITLE
How to fake a network error which is represented by an Exception thrown?

### ISSUE THREAD

**Issue by PureKrome** [maxkagamine/Moq.Contrib.HttpClient#7]
Heya!

An `HttpClient` can throw an exception, under certain circumstances. Is there a way to do that with this library?

**Comment by maxkagamine** [comment]
Hi! You can use the standard Moq `Throws()` to cause the handler to throw an exception:

```csharp
var handler = new Mock<HttpMessageHandler>();
var client = handler.CreateClient();

handler.SetupAnyRequest()
    .Throws<HttpRequestException>();

Func<Task> attempt = () => client.GetAsync("http://example.com");
await attempt.Should().ThrowAsync<HttpRequestException>();
```

Or if you want to get fancy:

```csharp
var inner = new System.Net.Sockets.SocketException((int)System.Net.Sockets.SocketError.ConnectionRefused);
handler.SetupAnyRequest()
    .Throws(new HttpRequestException(inner.Message, inner));
```

**Comment by PureKrome** [comment]
🤔 hmm.. i tried to do that but kept getting something like "no response was returned" or something .. hmm ...

**Comment by maxkagamine** [comment]
`Expected System.Net.Http.HttpRequestException, but found System.InvalidOperationException with message "Handler did not return a response message."` ?

Try `new Mock<HttpMessageHandler>(MockBehavior.Strict);` and see if you get a MockException "All invocations on the mock must have a corresponding setup". Might just not be matching the setup.
